### ISSUE TITLE
No such device or address (os error 6) during boot

### ISSUE THREAD

**Issue by saravanan30erd** [shimunn/fido2luks#14]
During the initrd process on system boot(Archlinux), I am running `fido2luks print-secret --pin` to get the response from solokey but getting the `No such device or address` error. But solokey is detected during initrd and I confirmed with `fido2luks connected` command.
https://github.com/saravanan30erd/solokey-full-disk-encryption/blob/master/hooks/skfde
In what cases we get this error?

**Comment by saravanan30erd** [comment]
I think its due to tty as its reading input for `--pin` from terminal.

**Comment by shimunn** [comment]
> I think its due to tty as its reading input for `--pin` from terminal.

Is that your intention? To read a PIN otherwise you may have misread the options and it is supposed to be `--bin` for binary. Otherwise the secret will be printed in it's hex representation and won't unlock your disk.

**Comment by saravanan30erd** [comment]
@shimunn thanks for quick reply.

I mentioned about `--pin` to unlock the solokey. If you provide `--pin`, then it asking for the solokey pin to provide via stdin (`Authenticator PIN:`). I think the error `No such device or address` is related to tty & stdin since the initrd doesn't have tty.

**Comment by shimunn** [comment]
I see. I have to admit that PIN support was a bit of an afterthought and is therefore not very well thought out. Anyway I've added another flag `--pin-source` that would allow you to specify a file or `/dev/stdin` to read the PIN from on a [separate branch](https://github.com/shimunn/fido2luks/tree/pin_source) and would appreciate your feedback, especially if you know of an neater way to obtain the PIN.

**Comment by saravanan30erd** [comment]
Sure, I will try with newly added env `FIDO2LUKS_PIN` and let you know.

However I removed the PIN in solokey and tried without `--pin` to cross-check, and I am not getting that `No such device` error now. But the command throws the following error `authenticator error: Error while decoding CBOR from device.` now.

It works when I run this command `print-secret` in normal mode and only throws the decode error during initrd process during boot.

**Comment by shimunn** [comment]
> However I removed the PIN in solokey and tried without --pin to cross-check, and I am not getting that No such device error now. But the command throws the following error authenticator error: Error while decoding CBOR from device. now.

I'm guessing [FIDO2LUKS_CREDENTIAL_ID](https://github.com/saravanan30erd/solokey-full-disk-encryption/blob/master/hooks/skfde#L9) stays empty, which can result in that error.

> Note: Also `fido2luks credential` works perfectly in initrd boot stage.

I don't see a reason why you would want to run that during boot. The idea is that you generate a credential during setup store it in a config, then use it to add a secret to your LUKS header. The same credential will then be used every time you boot

**Comment by saravanan30erd** [comment]
Due to some reason,  env FIDO2LUKS_CREDENTIAL_ID is not working in boot stage. so I m passing it in direct cmd line `fido2luks print-secret XXXXXXX --salt string:xxxx` 

Regarding `credential`, you are correct. But I just tried this command in boot bcoz it mentioned here #10 that `credential` having this same error. so its just for test and it works.

**Comment by saravanan30erd** [comment]
Now I am able to unlock the luks root partition with solokey during boot.
I will try `FIDO2LUKS_PIN` and update the output. 

But I would like to add one concern here, if we set PIN using file or env variable then authenticator PIN will be ended in initrd file that raises security concern. It would be better to prompt for PIN to type manually from keyboard same as `--pin`.
In LUKS encrypted disk, If I set normal passphrase as key then it prompts for passphrase during initrd boot stage. I checked  and the encrypt hook (https://wiki.archlinux.org/index.php/Dm-crypt/System_configuration#mkinitcpio) is used and its using `read` command to prompt for passphrase and it works in initrd stage. May be same logic behind `read` can help here for `--pin`.

**Comment by saravanan30erd** [comment]
@shimunn  I tried the `--pin-source` option and also env `FIDO2LUKS_PIN_SOURCE` in `pin_source` branch but it is not working, getting pin not provided error.

I found a way to read the std input in initrd boot stage using `read` command. It would be great if you provide option to pass the pin as argument value, something like this `--pin <authenticator pin>`

**Comment by shimunn** [comment]
You should be able to do something like this:

`echo "$PIN" | fido2luks print-secret --pin --pin-source /dev/stdin`

**Comment by saravanan30erd** [comment]
I tried this option `--pin --pin-source /dev/stdin` for both `credential` and `print-secret` and its giving the following error,

`authenticator error: Error while decoding CBOR from device.`

Additionally  please consider to pass the pin as string value like this,
`fido2luks print-secret <credential> --pin --pin-source <PIN as string>`

It would be straight forward.

**Comment by saravanan30erd** [comment]
@shimunn  I added another option `--pin-input` to pass authenticator pin value in cli itself as string.

`fido2luks credential --pin --pin-input <PIN value>`

It works fine. I raised the changes in PR #15, waiting for your feedback.

**Comment by shimunn** [comment]
> I tried this option `--pin --pin-source /dev/stdin` for both `credential` and `print-secret` and its giving the following error,
> 
> `authenticator error: Error while decoding CBOR from device.`

Sorry for the late answer, I had a busy week. If you compile the project in debug mode you'll get the error code which in your case would have been:

`Device returned error: CborError: 0x31: PIN Invalid.)`

because if you use echo as I suggested earlier the PIN will be terminated by a new line which of course isn't correct. But if you use printf instead(which doesn't append an \n) you get the expected result:

```
printf 1234 | cargo run -- print-secret --pin --pin-source /dev/stdin --salt 'string:issue14'
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/fido2luks print-secret --pin --pin-source /dev/stdin --salt 'string:issue14'`
b1327e79ae2a02b8b00b65d256e0fa46584af124cb649d5dc2cee94e867831c2
```

> 
> Additionally please consider to pass the pin as string value like this,
> `fido2luks print-secret <credential> --pin --pin-source <PIN as string>`
> 
> It would be straight forward.

It maybe straight forward but not a good idea to pass secrets such as you PIN around as command line parameter which would be visible to all processes on your system. Therefore I'd much prefer to leave it as is, being more secure and versatile.

**Comment by saravanan30erd** [comment]
@shimunn `/dev/stdin` will not work in initrd stage as this device not exists in initrd (same as tty issue).

However I passed the pin via file using `--pin-source`(after removing \n at end of file) and it works fine. In my case, file option works fine and I will continue to use this one.

Also tested the `/dev/stdin` with printf and it also works fine, you can merge the `pin_source` branch.
thanks.
