### ISSUE TITLE
Create package for Archlinux

### ISSUE THREAD

**Issue by saravanan30erd** [shimunn/fido2luks#16]
@shimunn 

I would like to support for creating the archlinux package for fido2luks, so it will be available via pacman install.
Please provide your input.

**Comment by saravanan30erd** [comment]
@shimunn  raised PR #17  for creating the package for Archlinux. Please check it.

**Comment by saravanan30erd** [comment]
@shimunn  I submitted the package to AUR, it might take time to move into community repo.

https://aur.archlinux.org/packages/fido2luks/

Could you provide your AUR username? so I can add you as `maintainer`.

Also we can automatically upload the package version details whenever new versions/tags created in this project.

**Comment by shimunn** [comment]
Thanks for publishing, here is my account: https://aur.archlinux.org/account/shimun

**Comment by saravanan30erd** [comment]
@shimunn added you in maintainer list, you can update the PKGBUILD whenever new version released here.

Thank you.

**Comment by saravanan30erd** [comment]
@shimunn  AUR commented to fix the source url.

I think this fix #18 will work for that.
