### ISSUE TITLE
Need for more Documentation

### ISSUE THREAD

**Issue by jaystrictor** [shimunn/fido2luks#19]
Hello, and thank you for working on and providing this software!

I want to use a FIDO2 Stick for decrypting my LUKS device on ArchLinux, but I must admit that I have few knowledge about FIDO2 internals and how to do the setup. I would love to be pointed to some more documentation. I couldn't find much.

Here is what I want to do:
I currently have an encrypted LUKS partition (not the root partition) where /home resides in. Usually I decrypt it by entering the passphrase during boot. Now I want to store the FIDO2LUKS key into a second keyslot, such that I can decrypt /home during boot either by providing the password or by using the FIDO2 stick.

What I have done so far:
1. I installed fido2luks
```
$ yay -S fido2luks
```
2. I tested the connection with
```
$ 
$ fido2luks connected
Found 1 devices
$ 
```
3. Generated a new credential:
```
$ 
$ fido2luks credential
15c9bec7284a5a09e0904006fea70dfe1daac52ec9dd94888c71a9f0d78310fd8c82d61d1df3520808fe832894664533262dae2262619c18ec0141da2be756214b5eaf010000
$ 
```
4. Trying to add a keyslot to the LUKS header:
```
$ 
$ sudo fido2luks add-key /dev/sda2 15c9bec7284a5a09e0904006fea70dfe1daac52ec9dd94888c71a9f0d78310fd8c82d61d1df3520808fe832894664533262dae2262619c18ec0141da2be756214b5eaf010000
Current password: 
^C
$ 
```

In Step 4, I type in a password for an already existing keyslot of the LUKS device. After that nothing happend. Tapping the FIDO2 stick also does nothing. So I canceled the program with Ctrl+C. What is supposed to happen?

**Comment by shimunn** [comment]
Try using `fido2luks -i add-key` calling it without `-i` will cause it to read the password using systemd-ask-password. But I agree the CLI and some another features need more/clearer documentation.

**Comment by jaystrictor** [comment]
Using `-i` works. Now I get
```
$ 
$ sudo fido2luks -i add-key /dev/sda2 15c9bec7284a5a09e0904006fea70dfe1daac52ec9dd94888c71a9f0d78310fd8c82d61d1df3520808fe832894664533262dae2262619c18ec0141da2be756214b5eaf010000
Current password: 
Password: 
Password (again): 
Added to key to device /dev/sda2, slot: 1
$ 
```

However, I don't want to provide another password. I do not want to have two factors to authenticate, just one (the FIDO2 stick). How can I achieve that?

**Comment by shimunn** [comment]
If you don't want a password just add  `FIDO2LUKS_SALT="string:"` as described [here](https://github.com/shimunn/fido2luks#password-less). The part after `string:` being the password you set during `add-key` which may also be empty.

**Comment by gbdlin** [comment]
Also, some theory of operation would be great, as right now it is not trivial for user to understand how exactly his data is protected (is response from the FIDO2 device used for decryption, so lack of response or invalid one will make decryption impossible? Is the response from FIDO2 device always the same or does the key rotate in some way? Do you need separate slot for every FIDO2 device you want to enroll? Can you have different passwords? How exactly does the decryption process look like? Is there automatic fallback for credentials stored in other LUKS slots?)

**Comment by digital-mystik** [comment]
> If you don't want a password just add `FIDO2LUKS_SALT="string:"` to /etc/fido2luks.conf as described [here](https://github.com/shimunn/fido2luks#password-less). The part after `string:` being the password you set during `add-key` which may also be empty.

Sorry to bump an old issue, but I have run into a similar situation as OP. Adding `FIDO2LUKS_SALT="string:"` skips the key password prompt (I have it set to empty for passwordless login), but after the fido2 confirmation, it asks for my original password (other LUKS slot). Is there a way to do either or; as in if my fido2 key is connected, that is all that is needed, and if it's not connected, it drops back to the regular password authentication? 

Great project by the way!

**Comment by shimunn** [comment]
I haven't really thought about that use case til now, guess it makes sense that you might want to use an standard password if you're not using 2FA anyway. 

There is no builtin way to do what you're asking for but the utilities for scripting such functionality are there. 
`fido2luks connected` will exit with 0 if there is an device connected or otherwise with 1

**Comment by digital-mystik** [comment]
Just noticed that if there are two keyslots in use (one being fido2 and the other a password), it will eventually drop back to the password prompt after enough time has passed.
