### ISSUE TITLE
Invalid message or item length

### ISSUE THREAD

**Issue by wmutschl** [shimunn/fido2luks#26]
Hi, I am trying to follow your README to install `fido2luks`, but I cannot succeed. Maybe you can help me out.
What I did:

### Step 1: Install packages 
```
sudo dnf install clang cargo cryptsetup-devel -y
```
No problem.

### Step 2: Clone repository and install using cargo

```
git clone https://github.com/shimunn/fido2luks.git 
cd fido2luks
sudo -E cargo install -f --path . --root /usr
```
No problem.

### Step 3: Create credential with --pin option
```
fido2luks credential
#AuthenticatorError { cause: FidoError(
#
#This operating requires a PIN but none was provided.) }

fido2luks credential --pin
#Authenticator PIN: 
#AuthenticatorError { cause: FidoError(FidoError(
#
#Device returned error: CborError: 0x3: Invalid message or item length.)
#
#Error while decoding CBOR from device.) }
```

Am I doing something wrong here?

**Comment by shimunn** [comment]
I don't think so, what kind of authenicator are you using?

**Comment by madonius** [comment]
Hi, I would like to reopen this issue since I have:
```
$ > ykinfo -v
version: 5.4.2
```
and face the exact same problem.
@wmutschl did you have any luck getting it to work?

**Comment by geneerik** [comment]
> Hi, I would like to reopen this issue since I have:
> 
> ```
> $ > ykinfo -v
> version: 5.4.2
> ```
> 
> and face the exact same problem.
> @wmutschl did you have any luck getting it to work?

Hi there!  I was able to get mine working after testing with the ctap hmac example as descibed here:
https://github.com/shimunn/fido2luks/issues/10#issuecomment-619146877

though the key was unlocked, it timed out as here:
```
user@host:~/ctap$ cargo run --all-features --example=hmac
   Compiling ctap_hmac v0.4.0 (/home/ptuser/ctap)
    Finished dev [unoptimized + debuginfo] target(s) in 4.21s
     Running `target/debug/examples/hmac`
Authorize using your device
thread 'main' panicked at 'Failed to request credential: FidoError(FidoError(

Device returned error: CborError: 0x3a: The current operation has timed out.)

Error while decoding CBOR from device.)', examples/hmac.rs:37:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This took some time before showing an error.  What i realized is that the yubikey was waiting for a touch input to unlock it even though the pin had been entered.  Once i touch it during the example run, the output looked like this:
```
user@host:~/ctap$ cargo run --all-features --example=hmac
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `target/debug/examples/hmac`
Authorize using your device
Credential: xxxxxxxxxxxxxxxx
Note: You can pass this credential as first argument in order to reproduce results
Type in your message: xxxxxxxxx
Authorize using your device
Hash: xxxxxxxxxxxxxx
```

After getting to to work, i realized my silly mistake. However, I do not get the `Authorize using your device` message from fido2luks.  For this reason, I believe a new issue should be opened in my case.  Could you also try this @madonius and see if you can get the hmac example to work with the pin patch described in the link?  You would touch the yubikey when the `Authorize using your device` message appears.

**Comment by geneerik** [comment]
one more detail to add to this note before referencing in a new ticket.  With or without updating ctap I was able to get this working.  

The error I get looks like the following:
```
user@host:~$ echo '1234' | fido2luks credential --pin --pin-source /dev/stdin
AuthenticatorError { cause: FidoError(FidoError(

Device returned error: CborError: 0x3: Invalid message or item length.)

Error while decoding CBOR from device.) }
```

The error message given is not so useful, but makes sense in the context, because it seems the error message is trying to tell the user they did not include a required bit of info making the message that was sent to the token invalid.  The infor in this case is the user name (credential name).  Once this is added, the credential is generated correctly.
```
user@host:~$ echo '1234' | fido2luks credential --pin --pin-source /dev/stdin some_credential_name
xxxxxxxxxxx
```

I will open a new issue referencing this, l but im leaving my debugging notes in case they are useful to someone, such as @madonius

**Comment by shimunn** [comment]
Thanks for your debugging efforts! So it seems like your Yubikey requires a non empty user_name which sort of makes sense since hmac enabled credentials are resident credentials but isn't required by spec.
