### ISSUE TITLE
credential command not enforcing required name parameter

### ISSUE THREAD

**Issue by geneerik** [shimunn/fido2luks#32]
See #26 
It seems the `fido2luks credential` command used to generate new credentials is resulting in an error message that is a bit cryptic if no name for the credential is supplied. The parameter is currently marked as optional, but if not provided and no value is set in the FIDO2LUKS_CREDENTIAL_NAME environmental variable the following occurs:
```
user@host:~$ echo '1234' | fido2luks credential --pin --pin-source /dev/stdin
AuthenticatorError { cause: FidoError(FidoError(

Device returned error: CborError: 0x3: Invalid message or item length.)

Error while decoding CBOR from device.) }
```
The FIDO2 token in use is a yubikey running on firmware 5.2.7(`YubiKey 5 Nano (5.2.7) [OTP+FIDO+CCID]`).

**Comment by geneerik** [comment]
Of note: it would be helpful if there was some kind of indicator that fido2luks is waiting on the device, such as when the device is awaiting my approval of authorization, such as touching the yubikey.  At the moment, there is no indication that this might be the case.  The user is left to wait with no indication of status until they authorize or a time out occurs resulting in a cbor error.  something such as `Authorize using your device` would be helpful to let users know fido2luks is in a waiting state.

**Comment by shimunn** [comment]
5496c4e61b211206c6fbd90e50e41cf490a5da3e will set the credential name to `fido2luks` if no other value is provided. This should fix the issue, even though I don't think it's actually a fido2luks issue but rather one in Yubicos firmware since the FIDO2 spec does not require a credential name.
