### ISSUE TITLE
no need to read password twice

### ISSUE THREAD

**Issue by mmahut** [shimunn/fido2luks#9]
With the current single implementation of ```read_password``` fido2luks ask for the password twice. This is not needed in every case, such as inputting the old secret, which we should just check and check for fail.

**Comment by shimunn** [comment]
Not needed but not harmful either, I'll start working on those kinds of issues once I've got some more free time which wont be the case for the next two months. But I'm happy to accept PRs if somebody needs this now.

**Comment by mmahut** [comment]
Indeed, just a cosmetic issue.

**Comment by shimunn** [comment]
done bb7ee7c1cea23ac2204859c37ecb186c0542ad23
